version: '3.9'

services:
  web:
    image: masaim24/hello-devops:latest
    container_name: hello-devops-app
    ports:
      - "5000:5000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: hello-devops-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  prometheus:
    image: prom/prometheus:latest
    container_name: hello-devops-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - web

  grafana:
    image: grafana/grafana:latest
    container_name: hello-devops-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
